// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package commands

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (answerQuiz) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*answerQuiz) UnmarshalJSON([]byte) error        { return nil }
func (answerQuiz) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*answerQuiz) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_answerQuiz *answerQuiz

func (courseAndTopic) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*courseAndTopic) UnmarshalJSON([]byte) error        { return nil }
func (courseAndTopic) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*courseAndTopic) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_courseAndTopic *courseAndTopic

func (executeTaskRequest) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*executeTaskRequest) UnmarshalJSON([]byte) error        { return nil }
func (executeTaskRequest) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*executeTaskRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_executeTaskRequest *executeTaskRequest

func (executeTaskResponse) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*executeTaskResponse) UnmarshalJSON([]byte) error        { return nil }
func (executeTaskResponse) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*executeTaskResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_executeTaskResponse *executeTaskResponse

func (submitQuizRequest) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*submitQuizRequest) UnmarshalJSON([]byte) error        { return nil }
func (submitQuizRequest) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*submitQuizRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_submitQuizRequest *submitQuizRequest

func (submitTaskRequest) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*submitTaskRequest) UnmarshalJSON([]byte) error        { return nil }
func (submitTaskRequest) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*submitTaskRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_submitTaskRequest *submitTaskRequest
