// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package queries

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries(in *jlexer.Lexer, out *topic) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "course_id":
			out.CourseID = string(in.String())
		case "title":
			out.Title = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "order_number":
			out.OrderNumber = int(in.Int())
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "updated_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries(out *jwriter.Writer, in topic) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"course_id\":"
		out.RawString(prefix)
		out.String(string(in.CourseID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"order_number\":"
		out.RawString(prefix)
		out.Int(int(in.OrderNumber))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v topic) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v topic) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *topic) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *topic) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries(l, v)
}
func easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries1(in *jlexer.Lexer, out *taskSubmission) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "task_id":
			out.TaskID = string(in.String())
		case "user_id":
			out.UserID = string(in.String())
		case "input":
			out.Input = string(in.String())
		case "passed":
			out.Passed = bool(in.Bool())
		case "error":
			if in.IsNull() {
				in.Skip()
				out.Error = nil
			} else {
				if out.Error == nil {
					out.Error = new(string)
				}
				*out.Error = string(in.String())
			}
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries1(out *jwriter.Writer, in taskSubmission) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"task_id\":"
		out.RawString(prefix)
		out.String(string(in.TaskID))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.String(string(in.UserID))
	}
	{
		const prefix string = ",\"input\":"
		out.RawString(prefix)
		out.String(string(in.Input))
	}
	{
		const prefix string = ",\"passed\":"
		out.RawString(prefix)
		out.Bool(bool(in.Passed))
	}
	{
		const prefix string = ",\"error\":"
		out.RawString(prefix)
		if in.Error == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Error))
		}
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v taskSubmission) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v taskSubmission) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *taskSubmission) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *taskSubmission) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries1(l, v)
}
func easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries2(in *jlexer.Lexer, out *quizz) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "topic_id":
			out.TopicID = string(in.String())
		case "question":
			out.Question = string(in.String())
		case "options":
			if in.IsNull() {
				in.Skip()
				out.Options = nil
			} else {
				in.Delim('[')
				if out.Options == nil {
					if !in.IsDelim(']') {
						out.Options = make([]string, 0, 4)
					} else {
						out.Options = []string{}
					}
				} else {
					out.Options = (out.Options)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Options = append(out.Options, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "answers":
			if in.IsNull() {
				in.Skip()
				out.Answers = nil
			} else {
				in.Delim('[')
				if out.Answers == nil {
					if !in.IsDelim(']') {
						out.Answers = make([]bool, 0, 64)
					} else {
						out.Answers = []bool{}
					}
				} else {
					out.Answers = (out.Answers)[:0]
				}
				for !in.IsDelim(']') {
					var v2 bool
					v2 = bool(in.Bool())
					out.Answers = append(out.Answers, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "multiple_choice":
			out.MultipleChoice = bool(in.Bool())
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "updated_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries2(out *jwriter.Writer, in quizz) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"topic_id\":"
		out.RawString(prefix)
		out.String(string(in.TopicID))
	}
	{
		const prefix string = ",\"question\":"
		out.RawString(prefix)
		out.String(string(in.Question))
	}
	{
		const prefix string = ",\"options\":"
		out.RawString(prefix)
		if in.Options == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.Options {
				if v3 > 0 {
					out.RawByte(',')
				}
				out.String(string(v4))
			}
			out.RawByte(']')
		}
	}
	if len(in.Answers) != 0 {
		const prefix string = ",\"answers\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v5, v6 := range in.Answers {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.Bool(bool(v6))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"multiple_choice\":"
		out.RawString(prefix)
		out.Bool(bool(in.MultipleChoice))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v quizz) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v quizz) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *quizz) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *quizz) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries2(l, v)
}
func easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries3(in *jlexer.Lexer, out *getTopicTasksRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "CourseID":
			out.CourseID = string(in.String())
		case "TopicID":
			out.TopicID = string(in.String())
		case "Order":
			out.Order = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries3(out *jwriter.Writer, in getTopicTasksRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"CourseID\":"
		out.RawString(prefix[1:])
		out.String(string(in.CourseID))
	}
	{
		const prefix string = ",\"TopicID\":"
		out.RawString(prefix)
		out.String(string(in.TopicID))
	}
	{
		const prefix string = ",\"Order\":"
		out.RawString(prefix)
		out.Int(int(in.Order))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getTopicTasksRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getTopicTasksRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getTopicTasksRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getTopicTasksRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries3(l, v)
}
func easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries4(in *jlexer.Lexer, out *getTopicQuizzesResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "quizzes":
			if in.IsNull() {
				in.Skip()
				out.Quizzes = nil
			} else {
				in.Delim('[')
				if out.Quizzes == nil {
					if !in.IsDelim(']') {
						out.Quizzes = make([]quizz, 0, 0)
					} else {
						out.Quizzes = []quizz{}
					}
				} else {
					out.Quizzes = (out.Quizzes)[:0]
				}
				for !in.IsDelim(']') {
					var v7 quizz
					(v7).UnmarshalEasyJSON(in)
					out.Quizzes = append(out.Quizzes, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "passed":
			out.Passed = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries4(out *jwriter.Writer, in getTopicQuizzesResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"quizzes\":"
		out.RawString(prefix[1:])
		if in.Quizzes == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.Quizzes {
				if v8 > 0 {
					out.RawByte(',')
				}
				(v9).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"passed\":"
		out.RawString(prefix)
		out.Bool(bool(in.Passed))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getTopicQuizzesResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getTopicQuizzesResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getTopicQuizzesResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getTopicQuizzesResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries4(l, v)
}
func easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries5(in *jlexer.Lexer, out *getTopicQuizzesRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "CourseID":
			out.CourseID = string(in.String())
		case "TopicID":
			out.TopicID = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries5(out *jwriter.Writer, in getTopicQuizzesRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"CourseID\":"
		out.RawString(prefix[1:])
		out.String(string(in.CourseID))
	}
	{
		const prefix string = ",\"TopicID\":"
		out.RawString(prefix)
		out.String(string(in.TopicID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getTopicQuizzesRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getTopicQuizzesRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getTopicQuizzesRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getTopicQuizzesRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries5(l, v)
}
func easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries6(in *jlexer.Lexer, out *getTopicContentRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "CourseID":
			out.CourseID = string(in.String())
		case "TopicID":
			out.TopicID = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries6(out *jwriter.Writer, in getTopicContentRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"CourseID\":"
		out.RawString(prefix[1:])
		out.String(string(in.CourseID))
	}
	{
		const prefix string = ",\"TopicID\":"
		out.RawString(prefix)
		out.String(string(in.TopicID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getTopicContentRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getTopicContentRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getTopicContentRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getTopicContentRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries6(l, v)
}
func easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries7(in *jlexer.Lexer, out *getTaskResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "topic_id":
			out.TopicID = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "difficulty_level":
			out.DifficultyLevel = string(in.String())
		case "starter_code":
			out.StarterCode = string(in.String())
		case "expected_output":
			if in.IsNull() {
				in.Skip()
				out.ExpectedOutput = nil
			} else {
				if out.ExpectedOutput == nil {
					out.ExpectedOutput = new(string)
				}
				*out.ExpectedOutput = string(in.String())
			}
		case "order_number":
			out.OrderNumber = int(in.Int())
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "updated_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		case "test_cases":
			out.TestCases = bool(in.Bool())
		case "language":
			out.Language = string(in.String())
		case "solved":
			out.Solved = bool(in.Bool())
		case "submission":
			if in.IsNull() {
				in.Skip()
				out.Submission = nil
			} else {
				if out.Submission == nil {
					out.Submission = new(taskSubmission)
				}
				(*out.Submission).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries7(out *jwriter.Writer, in getTaskResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"topic_id\":"
		out.RawString(prefix)
		out.String(string(in.TopicID))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"difficulty_level\":"
		out.RawString(prefix)
		out.String(string(in.DifficultyLevel))
	}
	{
		const prefix string = ",\"starter_code\":"
		out.RawString(prefix)
		out.String(string(in.StarterCode))
	}
	{
		const prefix string = ",\"expected_output\":"
		out.RawString(prefix)
		if in.ExpectedOutput == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.ExpectedOutput))
		}
	}
	{
		const prefix string = ",\"order_number\":"
		out.RawString(prefix)
		out.Int(int(in.OrderNumber))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"test_cases\":"
		out.RawString(prefix)
		out.Bool(bool(in.TestCases))
	}
	{
		const prefix string = ",\"language\":"
		out.RawString(prefix)
		out.String(string(in.Language))
	}
	{
		const prefix string = ",\"solved\":"
		out.RawString(prefix)
		out.Bool(bool(in.Solved))
	}
	{
		const prefix string = ",\"submission\":"
		out.RawString(prefix)
		if in.Submission == nil {
			out.RawString("null")
		} else {
			(*in.Submission).MarshalEasyJSON(out)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getTaskResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getTaskResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getTaskResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getTaskResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries7(l, v)
}
func easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries8(in *jlexer.Lexer, out *getCoursesListResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "courses":
			if in.IsNull() {
				in.Skip()
				out.Courses = nil
			} else {
				in.Delim('[')
				if out.Courses == nil {
					if !in.IsDelim(']') {
						out.Courses = make([]getCourseResponse, 0, 0)
					} else {
						out.Courses = []getCourseResponse{}
					}
				} else {
					out.Courses = (out.Courses)[:0]
				}
				for !in.IsDelim(']') {
					var v10 getCourseResponse
					(v10).UnmarshalEasyJSON(in)
					out.Courses = append(out.Courses, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries8(out *jwriter.Writer, in getCoursesListResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"courses\":"
		out.RawString(prefix[1:])
		if in.Courses == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.Courses {
				if v11 > 0 {
					out.RawByte(',')
				}
				(v12).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getCoursesListResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getCoursesListResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getCoursesListResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getCoursesListResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries8(l, v)
}
func easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries9(in *jlexer.Lexer, out *getCoursesListRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "limit":
			out.Limit = int(in.Int())
		case "offset":
			out.Offset = int(in.Int())
		case "categories_ids":
			if in.IsNull() {
				in.Skip()
				out.CategoriesIDs = nil
			} else {
				in.Delim('[')
				if out.CategoriesIDs == nil {
					if !in.IsDelim(']') {
						out.CategoriesIDs = make([]string, 0, 4)
					} else {
						out.CategoriesIDs = []string{}
					}
				} else {
					out.CategoriesIDs = (out.CategoriesIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v13 string
					v13 = string(in.String())
					out.CategoriesIDs = append(out.CategoriesIDs, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries9(out *jwriter.Writer, in getCoursesListRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Limit))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int(int(in.Offset))
	}
	{
		const prefix string = ",\"categories_ids\":"
		out.RawString(prefix)
		if in.CategoriesIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.CategoriesIDs {
				if v14 > 0 {
					out.RawByte(',')
				}
				out.String(string(v15))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getCoursesListRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getCoursesListRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getCoursesListRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getCoursesListRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries9(l, v)
}
func easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries10(in *jlexer.Lexer, out *getCourseResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "title":
			out.Title = string(in.String())
		case "image_url":
			if in.IsNull() {
				in.Skip()
				out.ImageURL = nil
			} else {
				if out.ImageURL == nil {
					out.ImageURL = new(string)
				}
				*out.ImageURL = string(in.String())
			}
		case "category":
			(out.Category).UnmarshalEasyJSON(in)
		case "description":
			out.Description = string(in.String())
		case "created_by":
			out.CreatedBy = string(in.String())
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "updated_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries10(out *jwriter.Writer, in getCourseResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"image_url\":"
		out.RawString(prefix)
		if in.ImageURL == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.ImageURL))
		}
	}
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix)
		(in.Category).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"created_by\":"
		out.RawString(prefix)
		out.String(string(in.CreatedBy))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getCourseResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getCourseResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getCourseResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getCourseResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries10(l, v)
}
func easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries11(in *jlexer.Lexer, out *getCourseDetailedResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "course":
			(out.Course).UnmarshalEasyJSON(in)
		case "topics":
			if in.IsNull() {
				in.Skip()
				out.Topics = nil
			} else {
				in.Delim('[')
				if out.Topics == nil {
					if !in.IsDelim(']') {
						out.Topics = make([]topic, 0, 0)
					} else {
						out.Topics = []topic{}
					}
				} else {
					out.Topics = (out.Topics)[:0]
				}
				for !in.IsDelim(']') {
					var v16 topic
					(v16).UnmarshalEasyJSON(in)
					out.Topics = append(out.Topics, v16)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries11(out *jwriter.Writer, in getCourseDetailedResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"course\":"
		out.RawString(prefix[1:])
		(in.Course).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"topics\":"
		out.RawString(prefix)
		if in.Topics == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v17, v18 := range in.Topics {
				if v17 > 0 {
					out.RawByte(',')
				}
				(v18).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getCourseDetailedResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getCourseDetailedResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getCourseDetailedResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getCourseDetailedResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries11(l, v)
}
func easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries12(in *jlexer.Lexer, out *getCategoriesListResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "categories":
			if in.IsNull() {
				in.Skip()
				out.Categories = nil
			} else {
				in.Delim('[')
				if out.Categories == nil {
					if !in.IsDelim(']') {
						out.Categories = make([]category, 0, 0)
					} else {
						out.Categories = []category{}
					}
				} else {
					out.Categories = (out.Categories)[:0]
				}
				for !in.IsDelim(']') {
					var v19 category
					(v19).UnmarshalEasyJSON(in)
					out.Categories = append(out.Categories, v19)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries12(out *jwriter.Writer, in getCategoriesListResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"categories\":"
		out.RawString(prefix[1:])
		if in.Categories == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v20, v21 := range in.Categories {
				if v20 > 0 {
					out.RawByte(',')
				}
				(v21).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v getCategoriesListResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v getCategoriesListResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *getCategoriesListResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *getCategoriesListResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries12(l, v)
}
func easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries13(in *jlexer.Lexer, out *category) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "created_by":
			out.CreatedBy = string(in.String())
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "updated_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries13(out *jwriter.Writer, in category) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"created_by\":"
		out.RawString(prefix)
		out.String(string(in.CreatedBy))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v category) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v category) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *category) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *category) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComRasikrrLearningPlatformGatewayInternalPortsHttpHandlersCoursesQueries13(l, v)
}
