// Code generated by "enumer -type=FileType -json -trimprefix FileType -transform=snake -output file_type_enumer.go"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _FileTypeName = "unknownavatarcoursefaq"

var _FileTypeIndex = [...]uint8{0, 7, 13, 19, 22}

const _FileTypeLowerName = "unknownavatarcoursefaq"

func (i FileType) String() string {
	if i >= FileType(len(_FileTypeIndex)-1) {
		return fmt.Sprintf("FileType(%d)", i)
	}
	return _FileTypeName[_FileTypeIndex[i]:_FileTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FileTypeNoOp() {
	var x [1]struct{}
	_ = x[FileTypeUnknown-(0)]
	_ = x[FileTypeAvatar-(1)]
	_ = x[FileTypeCourse-(2)]
	_ = x[FileTypeFaq-(3)]
}

var _FileTypeValues = []FileType{FileTypeUnknown, FileTypeAvatar, FileTypeCourse, FileTypeFaq}

var _FileTypeNameToValueMap = map[string]FileType{
	_FileTypeName[0:7]:        FileTypeUnknown,
	_FileTypeLowerName[0:7]:   FileTypeUnknown,
	_FileTypeName[7:13]:       FileTypeAvatar,
	_FileTypeLowerName[7:13]:  FileTypeAvatar,
	_FileTypeName[13:19]:      FileTypeCourse,
	_FileTypeLowerName[13:19]: FileTypeCourse,
	_FileTypeName[19:22]:      FileTypeFaq,
	_FileTypeLowerName[19:22]: FileTypeFaq,
}

var _FileTypeNames = []string{
	_FileTypeName[0:7],
	_FileTypeName[7:13],
	_FileTypeName[13:19],
	_FileTypeName[19:22],
}

// FileTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FileTypeString(s string) (FileType, error) {
	if val, ok := _FileTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _FileTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to FileType values", s)
}

// FileTypeValues returns all values of the enum
func FileTypeValues() []FileType {
	return _FileTypeValues
}

// FileTypeStrings returns a slice of all String values of the enum
func FileTypeStrings() []string {
	strs := make([]string, len(_FileTypeNames))
	copy(strs, _FileTypeNames)
	return strs
}

// IsAFileType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i FileType) IsAFileType() bool {
	for _, v := range _FileTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for FileType
func (i FileType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for FileType
func (i *FileType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("FileType should be a string, got %s", data)
	}

	var err error
	*i, err = FileTypeString(s)
	return err
}
